### ISSUE TITLE
state of map loaded

### ISSUE THREAD

**Issue by mrtyvz61** [Esri/esri-react-boot#5]
Hi thanks for such a great work. when ı start the project map loaded but in state doesnt change always false ?

**Comment by r-watkins** [comment]
Hi @mrtyvz61, I recently pushed some experimental changes so that a colleague of mine could work from it. I didn't think to use another branch. If you are using the current push then there will likely be some oddities like your issue. I'll be working on this for the next few days and hopefully re-release a stable version soon.

**Comment by r-watkins** [comment]
I got this worked out, should be good to go now
